services:
  gateway:
    build:
      context: ./gateway
      dockerfile: Dockerfile
    ports:
      - ${GATEWAY_PORT}:${GATEWAY_PORT}
    environment:
      - NOTES_SERVICE_URL=http://notes-service:${NOTES_SERVICE_PORT}
      - USER_SERVICE_URL=http://user-service:${USER_SERVICE_PORT}
      - GATEWAY_PORT=${GATEWAY_PORT}
    depends_on:
      - user-service
      - notes-service
    develop:
      watch: 
        - action: sync
          path: ./gateway
          target: /app
        - action: rebuild
          path: ./gateway
    networks:
      - gateway_network
    
  notes-service:
    build: 
      context: ./notes-service
      dockerfile: Dockerfile
    # ports:
    #   - ${NOTES_SERVICE_PORT}:${NOTES_SERVICE_PORT}
    environment:
      - NOTES_SERVICE_PORT=${NOTES_SERVICE_PORT}
      - DB_URL=postgres://${DB_USER}:${DB_PASSWORD}@database:${DB_PORT}/${DB_NAME}
      - GRPC_PORT=${GRPC_PORT}
      - GIN_MODE=${GIN_MODE}
    depends_on:
      - user-service
    develop:
      watch: 
        - action: sync
          path: ./notes-service
          target: /app
        - action: rebuild
          path: ./notes-service
    networks:
      - backend_network
      - gateway_network
    
  user-service:
    build: 
      context: ./user-service
      dockerfile: Dockerfile
    # ports:
    #   - ${USER_SERVICE_PORT}:${USER_SERVICE_PORT}
    environment:
      - DB_URL=postgres://${DB_USER}:${DB_PASSWORD}@database:5432/${DB_NAME}
      - REDIS_HOST=redis
      - REDIS_PORT=${REDIS_PORT}
      - JWT_SECRET=${JWT_SECRET}
      - USER_SERVICE_PORT=${USER_SERVICE_PORT}
      - GRPC_PORT=${GRPC_PORT}
    depends_on:
      - database
      - redis
    stop_grace_period: 30s
    develop:
      watch: 
        - action: sync
          path: ./user-service
          target: /app
        - action: rebuild
          path: ./user-service
    networks:
      - backend_network
      - redis_network
      - gateway_network

  database:
    image: postgres:latest
    # ports:
    #   - "5432:5432"
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    volumes:
      - db_data:/var/lib/postgresql/data
    networks:
      - backend_network

  redis:
    image: redis:latest
    networks:
      - redis_network
    # ports:
    #   - ${REDIS_PORT}:${REDIS_PORT}

networks:
  backend_network:
    driver: bridge
  redis_network:
    driver: bridge
  gateway_network:
    driver: bridge

volumes:
  db_data: